import io
from typing import Optional

try:
    from weasyprint import HTML
    HAS_WEASYPRINT = True
except ImportError:
    HAS_WEASYPRINT = False

    class HTML:
        def __init__(self, string=""):
            self.string = string
        def write_pdf(self):
            raise ImportError("weasyprint not installed. Install with: pip install weasyprint")


def _css() -> str:
    return """
    @page { margin: 2cm; size: A4; }
    body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11pt; line-height: 1.5; color: #1a1a1a; }
    h1 { font-size: 20pt; color: #4338ca; border-bottom: 2px solid #4338ca; padding-bottom: 6pt; }
    h2 { font-size: 14pt; color: #3730a3; margin-top: 20pt; }
    h3 { font-size: 11pt; color: #4f46e5; }
    table { width: 100%; border-collapse: collapse; margin: 10pt 0; }
    th { background: #eef2ff; padding: 6pt 8pt; text-align: left; font-size: 9pt; text-transform: uppercase; }
    td { padding: 6pt 8pt; border-bottom: 1px solid #e5e7eb; font-size: 10pt; }
    .meta { color: #6b7280; font-size: 9pt; margin-bottom: 15pt; }
    .score { display: inline-block; padding: 2pt 8pt; border-radius: 4pt; font-weight: bold; }
    .score-high { background: #dcfce7; color: #166534; }
    .score-mid { background: #fef3c7; color: #92400e; }
    .score-low { background: #fce4ec; color: #9a1b1b; }
    .footer { position: fixed; bottom: 0; width: 100%; text-align: center; color: #9ca3af; font-size: 8pt; }
    """


def _score_class(score: float) -> str:
    if score >= 0.7: return "score-high"
    if score >= 0.4: return "score-mid"
    return "score-low"


def material_report_html(material: dict) -> str:
    props = material.get("properties", {})
    comp = material.get("composition", {})
    syn = material.get("_synthesis", {})
    lp = material.get("lattice_parameters", {})

    rows = ""
    for el, data in comp.items():
        frac = data.get("atomic_fraction", data) if isinstance(data, dict) else data
        rows += f"<tr><td>{el}</td><td>{(frac*100):.1f}%</td></tr>"

    prop_rows = ""
    for k, v in props.items():
        prop_rows += f"<tr><td>{k.replace('_', ' ')}</td><td>{v.get('value', '')} {v.get('unit', '')}</td></tr>"

    score = syn.get("feasibility_score", 0)
    methods = ""
    for m in syn.get("recommended_methods", []):
        methods += f"<tr><td>{m['method'].replace('_', ' ')}</td><td>{m['estimated_temperature']}°C</td><td>{m['difficulty']}</td><td>{m['success_probability']*100:.0f}%</td></tr>"

    return f"""<!DOCTYPE html>
<html><body>
<h1>{material.get('formula', 'Unknown')}</h1>
<p class="meta">{material.get('name', '')} · Generated by AION · {material.get('created_at', '')}</p>
<h2>Crystal Data</h2>
<table>
<tr><td>Space Group</td><td>{material.get('space_group', '—')}</td></tr>
<tr><td>Crystal System</td><td>{material.get('crystal_system', '—')}</td></tr>
<tr><td>a</td><td>{lp.get('a', '—')} Å</td></tr>
<tr><td>b</td><td>{lp.get('b', '—')} Å</td></tr>
<tr><td>c</td><td>{lp.get('c', '—')} Å</td></tr>
<tr><td>Volume</td><td>{material.get('volume', '—')} Å³</td></tr>
<tr><td>Density</td><td>{material.get('density', '—')} g/cm³</td></tr>
</table>
<h2>Composition</h2>
<table><tr><th>Element</th><th>Atomic Fraction</th></tr>{rows}</table>
<h2>Properties</h2>
<table><tr><th>Property</th><th>Value</th></tr>{prop_rows}</table>
<h2>Synthesis Assessment</h2>
<p>Feasibility Score: <span class="score {_score_class(score)}">{score*100:.0f}%</span></p>
<h3>Recommended Methods</h3>
<table><tr><th>Method</th><th>Temperature</th><th>Difficulty</th><th>Success</th></tr>{methods}</table>
<p class="meta">{syn.get('thermodynamic_notes', '')}</p>
<h2>Risks</h2>
<ul>{"".join(f"<li>{r}</li>" for r in syn.get('risks', []))}</ul>
<div class="footer">AION Materials Discovery Platform · Confidential</div>
</body></html>"""


def experiment_report_html(experiment: dict) -> str:
    steps = "".join(
        f"<tr><td>{s['step_number']}</td><td>{s['step_type']}</td><td>{s['description']}</td><td>{'✅' if s.get('completed') else '⬜'}</td></tr>"
        for s in experiment.get("steps", [])
    )
    results = "".join(
        f"<tr><td>{r['result_type']}</td><td>{r.get('value', '')}</td><td>{r.get('unit', '')}</td><td>{r.get('characterization_method', '')}</td></tr>"
        for r in experiment.get("results", [])
    )

    return f"""<!DOCTYPE html>
<html><body>
<h1>Experiment: {experiment.get('name', '')}</h1>
<p class="meta">Material ID: {experiment.get('material_id')} · Status: {experiment.get('status', '')} · Created: {experiment.get('created_at', '')}</p>
<h2>Procedure Steps</h2>
<table><tr><th>#</th><th>Type</th><th>Description</th><th>Status</th></tr>{steps}</table>
<h2>Results</h2>
<table><tr><th>Type</th><th>Value</th><th>Unit</th><th>Method</th></tr>{results}</table>
<h2>Notes</h2>
<p>{experiment.get('notes', 'No notes recorded')}</p>
<div class="footer">AION Materials Discovery Platform · Confidential</div>
</body></html>"""


def generate_pdf(html_content: str) -> bytes:
    return HTML(string=html_content).write_pdf()
